name: test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - run: |
          echo $GITHUB_PATH
          du -sh /opt/hostedtoolcache/gcloud
          # find /opt/hostedtoolcache/gcloud
          # which gcloud
