name: test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: cache
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/gcloud
          key: gcloud
          save-always: true

      - if: ${{ !steps.cache.outputs.cache-hit }}
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - if: ${{ steps.cache.outputs.cache-hit }}
        name: gcloud from cache
        run: |
          echo "$(dirname $(which gcloud ))" >> $GITHUB_PATH

      - name: debug
        run: |
          gcloud --version
